### ISSUE TITLE
activerecord-4.2.4 breaks activerecord_enum

### ISSUE THREAD

**Issue by fruwe** [iangreenleaf/activerecord_enum#10]
hmm, seems to brake during migration

```
create_table :users do |t|
  t.enum :status, limit: ["active", "inactive"], default: "active", null: false
  t.timestamps null: false
end
```

causes

```
undefined method `split' for nil:NilClass/Users/chris/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:695:in `block in initialize_type_map'
/Users/chris/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activerecord-4.2.4/lib/active_record/type/type_map.rb:53:in `call'
/Users/chris/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activerecord-4.2.4/lib/active_record/type/type_map.rb:53:in `perform_fetch'
```

**Comment by fruwe** [comment]
as it turns out, it's not the version, but the order inside the Gemfile that was the culprit.

```
gem 'mysql2', '~> 0.3.20'
gem 'activerecord_enum'
```

works, but

```
gem 'activerecord_enum'
gem 'mysql2', '~> 0.3.20'
```

throws the "undefined method split" error.

Maybe this should be mentioned inside the documentation

**Comment by iangreenleaf** [comment]
Thanks for the bug report and the follow-up! Yes, that seems like something that should be in the docs. I'll add it there soon.
